### ISSUE TITLE
Partidos

### ISSUE THREAD

**Issue by jncorrea** [jncorrea/gop#100]
No se puede ver ningún partido por jugar, sin ingresar a "ver todos". Solo me salen las opciones "Crear partidos" y "Ver todos".

**Comment by migranda** [comment]
Mis partidos por jugar enlista todos los partidos con fecha superior a  la actual 2015-09-18 11:30:00 POR EJEMPLO.
![partidosok](https://cloud.githubusercontent.com/assets/12100782/9964801/fbf428aa-5df7-11e5-8257-82ac117eadc3.png)

**Comment by jncorrea** [comment]
![Uploading image.png…]()

**Comment by jncorrea** [comment]
Revísale bien, si se sube un issue no es por molestar, es porque algo no está funcionando como debería
![image](https://cloud.githubusercontent.com/assets/12261149/9965327/2e6d1fb4-5dfb-11e5-9946-ae7fc6984752.png)
