### ISSUE TITLE
Miembros de un grupo.

### ISSUE THREAD

**Issue by migranda** [jncorrea/gop#101]
La tabla de miembros de un grupo muestra usuarios duplicados, por ejemplo al asignar un nuevo adminisitrador,

**Comment by jncorrea** [comment]
Por favor Sube una captura de pantalla sobre esto porque no te entiendo muy bien a que te refieres

**Comment by jncorrea** [comment]
Cerrado en ed79822f088e955fe74c4ced45772ef5e8bee2cb
