### ISSUE TITLE
Buscar y listar los últimos 5 grupos modificados

### ISSUE THREAD

**Issue by migranda** [jncorrea/gop#67]
En el menú mostrar los últimos 5 grupos en los que se realizo un cambio, y además incluir la opción ver todos.

**Comment by jncorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/12261149/9835351/7f0f95f8-59ac-11e5-82c9-1868e149a22c.png)

**Comment by migranda** [comment]
Este es un warning de include/insertar_cancha linea 98 
if ($_POST['todos']==1) { 

Revisarlo please.
