### ISSUE TITLE
Modificaciones en Partidos

### ISSUE THREAD

**Issue by migranda** [jncorrea/gop#90]
1- Que cualquier integrante de un grupo pueda crear un partido.
2- Modificar el formulario crear partido. (Controlar horarios)
3 - Controlar lo responsivo en el menú de partidos.
4 - En comentarios cambiar la ruta de imagen  y hacerla responsiva.
5 - Enviar invitación de un partido  un usuario  solo cuando sea miembro del grupo (haya aceptado una invitación enviada)
6 - Ofertar cupos no funciona.
7 -Comentarios no funciona (Revisar caracteres especiales)
8 - Se crean 2 partidos iguales (Controlar)
9 -  Mostrar los ultimos 4 partidos y ver más.
10. Editar un partido (Revisar)

**Comment by jncorrea** [comment]
Cerrado en el commit 2502f6f17cc4be67088d2f371465c3d66d5c20e1
