### ISSUE TITLE
Configurar Perfil

### ISSUE THREAD

**Issue by jncorrea** [jncorrea/gop#96]
Cuando configuro mi perfil y no modifico la fecha, me toma un valor por defecto "1950-01-01" lo cual no está bien, porque afecta al porcentaje de avance de perfil.
![image](https://cloud.githubusercontent.com/assets/12261149/9938068/28bb838a-5d29-11e5-8cc9-cbd68aef7365.png)
El estado de las notificaciones pro defecto debería ser que está activado.
Cada vez que se guarda configurar el perfil, debería mostrar una notificación con el porcentaje del avance del mismo.

**Comment by migranda** [comment]
commit 3bd0c44fb3bf9119c321f90e52af217e1b4c1ef9
- La fecha 1950-01-01 es un valor por defecto y no cuenta como avance de perfil.
- Cuando el usuario se registra por primera vez su  estado de notificaciones inicia como activado.
- Al guardar los datos se registra un mensaje que indica sobre el avance del perfil en la ficha principal.
