### ISSUE TITLE
Listar grupos

### ISSUE THREAD

**Issue by jncorrea** [jncorrea/gop#99]
No lista correctamente los grupos, yo administro 4 y me aparecen 3.
![image](https://cloud.githubusercontent.com/assets/12261149/9953712/bf481028-5da8-11e5-94ba-017148cb22b0.png)

**Comment by migranda** [comment]
- Administración de 4 o más grupos.
- Desde la aplicación no se permite crear grupos iguales.
![grupos](https://cloud.githubusercontent.com/assets/12100782/9961369/c45a596c-5de5-11e5-9ba1-0720a89561d9.png)
